#!/bin/sh
python hellodjango/manage.py syncdb --noinput
python hellodjango/manage.py check_permissions
python mkadmin.py
python definesite.py
python mkcategorythreadpost.py
mkdir -p /home/dotcloud/data/media /home/dotcloud/data/static
python hellodjango/manage.py collectstatic --noinput